### ISSUE TITLE
Wrong syntaxe for client.py on README.md

### ISSUE THREAD

**Issue by tpetrone** [dwysocki/RTT#1]
Where it is:

> Then run from client
> `python client.py outdir all TCP 8888 name.host@example.com`

shouldn't be?

> Then run from client
> `python client.py outdir all TCP name.host@example.com 8888`

**Comment by dwysocki** [comment]
Looks like you're right @tpetrone. I've gone ahead and fixed it.

Thank you for pointing this out.

**Comment by tpetrone** [comment]
it was nothing, really
thank you very much for publishing this out!
